// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_3hs9nmWm7ZVJD5XyBJUm12YfWaRreFc',
    appId: '1:1065391381919:web:99d1e0a43c71006045f1aa',
    messagingSenderId: '1065391381919',
    projectId: 'authtutorial-81765',
    authDomain: 'authtutorial-81765.firebaseapp.com',
    storageBucket: 'authtutorial-81765.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZeAaKEfYJIcEone9pRGncTis9H56J3i4',
    appId: '1:1065391381919:android:18a22d151a2e48aa45f1aa',
    messagingSenderId: '1065391381919',
    projectId: 'authtutorial-81765',
    storageBucket: 'authtutorial-81765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsWa8MslqcDCsMN1gKEpl2OjhsBnJwwSE',
    appId: '1:1065391381919:ios:5df45987acd5b5b945f1aa',
    messagingSenderId: '1065391381919',
    projectId: 'authtutorial-81765',
    storageBucket: 'authtutorial-81765.appspot.com',
    iosBundleId: 'com.example.bookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAsWa8MslqcDCsMN1gKEpl2OjhsBnJwwSE',
    appId: '1:1065391381919:ios:4a8bc17806316c6745f1aa',
    messagingSenderId: '1065391381919',
    projectId: 'authtutorial-81765',
    storageBucket: 'authtutorial-81765.appspot.com',
    iosBundleId: 'com.example.bookingApp.RunnerTests',
  );
}
